export const raceTeams = [

  // ── F1 ───────────────────────────────────────────────────────────────────

  {
    number: 1,
    series: 'f1',
    season: 2026,
    team: 'McLaren',
    car_model: 'McLaren MCL40',
    class: 'F1',
    drivers: ['Lando Norris'],
  },
  {
    number: 81,
    series: 'f1',
    season: 2026,
    team: 'McLaren',
    car_model: 'McLaren MCL40',
    class: 'F1',
    drivers: ['Oscar Piastri'],
  },
  {
    number: 63,
    series: 'f1',
    season: 2026,
    team: 'Mercedes',
    car_model: 'Mercedes W17',
    class: 'F1',
    drivers: ['George Russell'],
  },
  {
    number: 12,
    series: 'f1',
    season: 2026,
    team: 'Mercedes',
    car_model: 'Mercedes W17',
    class: 'F1',
    drivers: ['Kimi Antonelli'],
  },
  {
    number: 16,
    series: 'f1',
    season: 2026,
    team: 'Ferrari',
    car_model: 'Ferrari SF-26',
    class: 'F1',
    drivers: ['Charles Leclerc'],
  },
  {
    number: 44,
    series: 'f1',
    season: 2026,
    team: 'Ferrari',
    car_model: 'Ferrari SF-26',
    class: 'F1',
    drivers: ['Lewis Hamilton'],
  },
  {
    number: 3,
    series: 'f1',
    season: 2026,
    team: 'Red Bull Racing',
    car_model: 'Red Bull RB22',
    class: 'F1',
    drivers: ['Max Verstappen'],
  },
  {
    number: 6,
    series: 'f1',
    season: 2026,
    team: 'Red Bull Racing',
    car_model: 'Red Bull RB22',
    class: 'F1',
    drivers: ['Isack Hadjar'],
  },
  {
    number: 23,
    series: 'f1',
    season: 2026,
    team: 'Williams',
    car_model: 'Williams FW48',
    class: 'F1',
    drivers: ['Alexander Albon'],
  },
  {
    number: 55,
    series: 'f1',
    season: 2026,
    team: 'Williams',
    car_model: 'Williams FW48',
    class: 'F1',
    drivers: ['Carlos Sainz'],
  },
  {
    number: 30,
    series: 'f1',
    season: 2026,
    team: 'Racing Bulls',
    car_model: 'Racing Bulls VCARB03',
    class: 'F1',
    drivers: ['Liam Lawson'],
  },
  {
    number: 41,
    series: 'f1',
    season: 2026,
    team: 'Racing Bulls',
    car_model: 'Racing Bulls VCARB03',
    class: 'F1',
    drivers: ['Arvid Lindblad'],
  },
  {
    number: 14,
    series: 'f1',
    season: 2026,
    team: 'Aston Martin',
    car_model: 'Aston Martin AMR26',
    class: 'F1',
    drivers: ['Fernando Alonso'],
  },
  {
    number: 18,
    series: 'f1',
    season: 2026,
    team: 'Aston Martin',
    car_model: 'Aston Martin AMR26',
    class: 'F1',
    drivers: ['Lance Stroll'],
  },
  {
    number: 31,
    series: 'f1',
    season: 2026,
    team: 'Haas',
    car_model: 'Haas VF-26',
    class: 'F1',
    drivers: ['Esteban Ocon'],
  },
  {
    number: 87,
    series: 'f1',
    season: 2026,
    team: 'Haas',
    car_model: 'Haas VF-26',
    class: 'F1',
    drivers: ['Oliver Bearman'],
  },
  {
    number: 27,
    series: 'f1',
    season: 2026,
    team: 'Audi',
    car_model: 'Audi R26',
    class: 'F1',
    drivers: ['Nico Hülkenberg'],
  },
  {
    number: 5,
    series: 'f1',
    season: 2026,
    team: 'Audi',
    car_model: 'Audi R26',
    class: 'F1',
    drivers: ['Gabriel Bortoleto'],
  },
  {
    number: 10,
    series: 'f1',
    season: 2026,
    team: 'Alpine',
    car_model: 'Alpine A526',
    class: 'F1',
    drivers: ['Pierre Gasly'],
  },
  {
    number: 43,
    series: 'f1',
    season: 2026,
    team: 'Alpine',
    car_model: 'Alpine A526',
    class: 'F1',
    drivers: ['Franco Colapinto'],
  },
  {
    number: 11,
    series: 'f1',
    season: 2026,
    team: 'Cadillac',
    car_model: 'Cadillac MAC-26',
    class: 'F1',
    drivers: ['Sergio Pérez'],
  },
  {
    number: 77,
    series: 'f1',
    season: 2026,
    team: 'Cadillac',
    car_model: 'Cadillac MAC-26',
    class: 'F1',
    drivers: ['Valtteri Bottas'],
  },

  // ── WRC ──────────────────────────────────────────────────────────────────

  {
    number: 33,
    series: 'wrc',
    season: 2026,
    team: 'Toyota Gazoo Racing WRT',
    car_model: 'Toyota GR Yaris Rally1',
    class: 'WRC',
    drivers: ['Elfyn Evans', 'Scott Martin'],
  },
  {
    number: 99,
    series: 'wrc',
    season: 2026,
    team: 'Toyota Gazoo Racing WRT',
    car_model: 'Toyota GR Yaris Rally1',
    class: 'WRC',
    drivers: ['Oliver Solberg', 'Elliott Edmondson'],
  },
  {
    number: 18,
    series: 'wrc',
    season: 2026,
    team: 'Toyota Gazoo Racing WRT',
    car_model: 'Toyota GR Yaris Rally1',
    class: 'WRC',
    drivers: ['Takamoto Katsuta', 'Aaron Johnston'],
  },
  {
    number: 1,
    series: 'wrc',
    season: 2026,
    team: 'Toyota Gazoo Racing WRT',
    car_model: 'Toyota GR Yaris Rally1',
    class: 'WRC',
    drivers: ['Sébastien Ogier', 'Vincent Landais'],
  },
  {
    number: 5,
    series: 'wrc',
    season: 2026,
    team: 'Toyota Gazoo Racing WRT2',
    car_model: 'Toyota GR Yaris Rally1',
    class: 'WRC',
    drivers: ['Sami Pajari', 'Marko Salminen'],
  },
  {
    number: 11,
    series: 'wrc',
    season: 2026,
    team: 'Hyundai Shell Mobis WRT',
    car_model: 'Hyundai i20 N Rally1',
    class: 'WRC',
    drivers: ['Thierry Neuville', 'Martijn Wydaeghe'],
  },
  {
    number: 16,
    series: 'wrc',
    season: 2026,
    team: 'Hyundai Shell Mobis WRT',
    car_model: 'Hyundai i20 N Rally1',
    class: 'WRC',
    drivers: ['Adrien Fourmaux', 'Alexandre Coria'],
  },
  {
    number: 69,
    series: 'wrc',
    season: 2026,
    team: 'Hyundai Shell Mobis WRT',
    car_model: 'Hyundai i20 N Rally1',
    class: 'WRC',
    drivers: ['Hayden Paddon', 'John Kennard'],
  },
  {
    number: 8,
    series: 'wrc',
    season: 2026,
    team: 'Hyundai Shell Mobis WRT',
    car_model: 'Hyundai i20 N Rally1',
    class: 'WRC',
    drivers: ['Esapekka Lappi', 'Enni Mälkönen'],
  },
  {
    number: 19,
    series: 'wrc',
    season: 2026,
    team: 'Hyundai Shell Mobis WRT',
    car_model: 'Hyundai i20 N Rally1',
    class: 'WRC',
    drivers: ['Dani Sordo', 'Cándido Carrera'],
  },
  {
    number: 4,
    series: 'wrc',
    season: 2026,
    team: 'M-Sport Ford WRT',
    car_model: 'Ford Puma Rally1',
    class: 'WRC',
    drivers: ['Mārtiņš Sesks', 'Renārs Francis'],
  },
  {
    number: 42,
    series: 'wrc',
    season: 2026,
    team: 'M-Sport Ford WRT',
    car_model: 'Ford Puma Rally1',
    class: 'WRC',
    drivers: ['Josh McErlean', 'Eoin Treacy'],
  },
  {
    number: 44,
    series: 'wrc',
    season: 2026,
    team: 'M-Sport Ford WRT',
    car_model: 'Ford Puma Rally1',
    class: 'WRC',
    drivers: ['Jon Armstrong', 'Shane Byrne'],
  },

  // ── WEC ──────────────────────────────────────────────────────────────────

  {
    number: 7,
    series: 'wec',
    season: 2026,
    team: 'Toyota Racing',
    car_model: 'Toyota TR010 Hybrid',
    class: 'Hypercar',
    drivers: ['Mike Conway', 'Kamui Kobayashi', 'Nyck de Vries'],
  },
  {
    number: 8,
    series: 'wec',
    season: 2026,
    team: 'Toyota Racing',
    car_model: 'Toyota TR010 Hybrid',
    class: 'Hypercar',
    drivers: ['Sébastien Buemi', 'Brendon Hartley', 'Ryo Hirakawa'],
  },
  {
    number: 50,
    series: 'wec',
    season: 2026,
    team: 'Ferrari AF Corse',
    car_model: 'Ferrari 499P',
    class: 'Hypercar',
    drivers: ['Antonio Fuoco', 'Miguel Molina', 'Nicklas Nielsen'],
  },
  {
    number: 51,
    series: 'wec',
    season: 2026,
    team: 'Ferrari AF Corse',
    car_model: 'Ferrari 499P',
    class: 'Hypercar',
    drivers: ['Alessandro Pier Guidi', 'James Calado', 'Antonio Giovinazzi'],
  },
  {
    number: 83,
    series: 'wec',
    season: 2026,
    team: 'AF Corse',
    car_model: 'Ferrari 499P',
    class: 'Hypercar',
    drivers: ['Yifei Ye', 'Robert Kubica', 'Phil Hanson'],
  },
  {
    number: 12,
    series: 'wec',
    season: 2026,
    team: 'Cadillac Hertz Team JOTA',
    car_model: 'Cadillac V-Series.R',
    class: 'Hypercar',
    drivers: ['Alex Lynn', 'Will Stevens', 'Norman Nato'],
  },
  {
    number: 38,
    series: 'wec',
    season: 2026,
    team: 'Cadillac Hertz Team JOTA',
    car_model: 'Cadillac V-Series.R',
    class: 'Hypercar',
    drivers: ['Earl Bamber', 'Sébastien Bourdais', 'Jack Aitken'],
  },
  {
    number: 15,
    series: 'wec',
    season: 2026,
    team: 'BMW M Team WRT',
    car_model: 'BMW M Hybrid V8',
    class: 'Hypercar',
    drivers: ['Kevin Magnussen', 'Raffaele Marciello', 'Dries Vanthoor'],
  },
  {
    number: 20,
    series: 'wec',
    season: 2026,
    team: 'BMW M Team WRT',
    car_model: 'BMW M Hybrid V8',
    class: 'Hypercar',
    drivers: ['Robin Frijns', 'René Rast', 'Sheldon van der Linde'],
  },
  {
    number: 35,
    series: 'wec',
    season: 2026,
    team: 'Alpine Endurance Team',
    car_model: 'Alpine A424',
    class: 'Hypercar',
    drivers: ['António Félix da Costa', 'Charles Milesi', 'Ferdinand Habsburg'],
  },
  {
    number: 36,
    series: 'wec',
    season: 2026,
    team: 'Alpine Endurance Team',
    car_model: 'Alpine A424',
    class: 'Hypercar',
    drivers: ['Frédéric Makowiecki', 'Jules Gounon', 'Victor Martins'],
  },
  {
    number: 93,
    series: 'wec',
    season: 2026,
    team: 'Peugeot TotalEnergies',
    car_model: 'Peugeot 9X8',
    class: 'Hypercar',
    drivers: ['Nick Cassidy', 'Paul Di Resta', 'Stoffel Vandoorne'],
  },
  {
    number: 94,
    series: 'wec',
    season: 2026,
    team: 'Peugeot TotalEnergies',
    car_model: 'Peugeot 9X8',
    class: 'Hypercar',
    drivers: ['Loïc Duval', 'Malthe Jakobsen', 'Théo Pourchaire'],
  },
  {
    number: 17,
    series: 'wec',
    season: 2026,
    team: 'Genesis Magma Racing',
    car_model: 'Genesis GMR-001',
    class: 'Hypercar',
    drivers: ['André Lotterer', 'Pipo Derani', 'Mathys Jaubert'],
  },
  {
    number: 19,
    series: 'wec',
    season: 2026,
    team: 'Genesis Magma Racing',
    car_model: 'Genesis GMR-001',
    class: 'Hypercar',
    drivers: ['Mathieu Jaminet', 'Paul-Loup Chatin', 'Daniel Juncadella'],
  },
  {
    number: 907,
    series: 'wec',
    season: 2026,
    team: 'Aston Martin THOR Team',
    car_model: 'Aston Martin Valkyrie',
    class: 'Hypercar',
    drivers: ['Harry Tincknell', 'Tom Gamble', 'Ross Gunn'],
  },
  {
    number: 909,
    series: 'wec',
    season: 2026,
    team: 'Aston Martin THOR Team',
    car_model: 'Aston Martin Valkyrie',
    class: 'Hypercar',
    drivers: ['Alex Riberas', 'Marco Sørensen', 'Roman De Angelis'],
  },
  {
    number: 21,
    series: 'wec',
    season: 2026,
    team: 'Vista AF Corse',
    car_model: 'Ferrari 296 LMGT3',
    class: 'LMGT3',
    drivers: ['François Heriau', 'Simon Mann', 'Alessio Rovera'],
  },
  {
    number: 54,
    series: 'wec',
    season: 2026,
    team: 'Vista AF Corse',
    car_model: 'Ferrari 296 LMGT3',
    class: 'LMGT3',
    drivers: ['Thomas Flohr', 'Francesco Castellacci', 'Davide Rigon'],
  },
  {
    number: 23,
    series: 'wec',
    season: 2026,
    team: 'Heart of Racing Team',
    car_model: 'Aston Martin Vantage LMGT3',
    class: 'LMGT3',
    drivers: ['Gray Newell', 'Kobe Pauwels', 'Jonny Adam'],
  },
  {
    number: 27,
    series: 'wec',
    season: 2026,
    team: 'Heart of Racing Team',
    car_model: 'Aston Martin Vantage LMGT3',
    class: 'LMGT3',
    drivers: ['Ian James', 'Zacharie Robichon', 'Mattia Drudi'],
  },
  {
    number: 32,
    series: 'wec',
    season: 2026,
    team: 'Team WRT',
    car_model: 'BMW M4 LMGT3',
    class: 'LMGT3',
    drivers: ['Darren Leung', 'Sean Gelael', 'Augusto Farfus'],
  },
  {
    number: 69,
    series: 'wec',
    season: 2026,
    team: 'Team WRT',
    car_model: 'BMW M4 LMGT3',
    class: 'LMGT3',
    drivers: ['Anthony McIntosh', 'Parker Thompson', 'Dan Harper'],
  },
  {
    number: 33,
    series: 'wec',
    season: 2026,
    team: 'TF Sport',
    car_model: 'Corvette Z06 LMGT3.R',
    class: 'LMGT3',
    drivers: ['Ben Keating', 'Nicky Catsburg', 'Jonny Edgar'],
  },
  {
    number: 34,
    series: 'wec',
    season: 2026,
    team: 'Racing Team Turkey by TF',
    car_model: 'Corvette Z06 LMGT3.R',
    class: 'LMGT3',
    drivers: ['Salih Yoluc', 'Charlie Eastwood', 'Peter Dempsey'],
  },
  {
    number: 10,
    series: 'wec',
    season: 2026,
    team: 'Garage 59',
    car_model: 'McLaren 720S LMGT3',
    class: 'LMGT3',
    drivers: ['Antares Au', 'Thomas Fleming', 'Marvin Kirchhoefer'],
  },
  {
    number: 58,
    series: 'wec',
    season: 2026,
    team: 'Garage 59',
    car_model: 'McLaren 720S LMGT3',
    class: 'LMGT3',
    drivers: ['Alexander West', 'Finn Gehrsitz', 'Benjamin Goethe'],
  },
  {
    number: 61,
    series: 'wec',
    season: 2026,
    team: 'Iron Lynx',
    car_model: 'Mercedes-AMG GT3',
    class: 'LMGT3',
    drivers: ['Rui Andrade', 'Maxime Martin', 'Martin Berry'],
  },
  {
    number: 79,
    series: 'wec',
    season: 2026,
    team: 'Iron Lynx',
    car_model: 'Mercedes-AMG GT3',
    class: 'LMGT3',
    drivers: ['Lin Hodenius', 'Matteo Cressoni', 'Johannes Zelger'],
  },
  {
    number: 77,
    series: 'wec',
    season: 2026,
    team: 'Proton Competition',
    car_model: 'Ford Mustang LMGT3',
    class: 'LMGT3',
    drivers: ['Ben Tucker', 'Gianmarco Leverato', 'Logan Sargeant'],
  },
  {
    number: 88,
    series: 'wec',
    season: 2026,
    team: 'Proton Competition',
    car_model: 'Ford Mustang LMGT3',
    class: 'LMGT3',
    drivers: ['Sebastian Priaulx'],
  },
  {
    number: 78,
    series: 'wec',
    season: 2026,
    team: 'Akkodis ASP',
    car_model: 'Lexus RC F LMGT3',
    class: 'LMGT3',
    drivers: ['Esteban Masson', 'Tom van Rompuy', 'Petru Umbrarescu'],
  },
  {
    number: 87,
    series: 'wec',
    season: 2026,
    team: 'Akkodis ASP',
    car_model: 'Lexus RC F LMGT3',
    class: 'LMGT3',
    drivers: ['José María López'],
  },
  {
    number: 91,
    series: 'wec',
    season: 2026,
    team: 'Manthey DK Engineering',
    car_model: 'Porsche 911 GT3 R LMGT3',
    class: 'LMGT3',
    drivers: ['Ayhancan Güven', 'James Cottingham', 'Timur Boguslavskiy'],
  },
  {
    number: 92,
    series: 'wec',
    season: 2026,
    team: 'The Bend Manthey',
    car_model: 'Porsche 911 GT3 R LMGT3',
    class: 'LMGT3',
    drivers: ['Richard Lietz', 'Riccardo Pera', 'Yasser Shahin'],
  },

  // ── IMSA ─────────────────────────────────────────────────────────────────

  {
    number: 7,
    series: 'imsa',
    season: 2026,
    team: 'Porsche Penske Motorsport',
    car_model: 'Porsche 963',
    class: 'GTP',
    drivers: ['Felipe Nasr', 'Julien Andlauer', 'Laurin Heinrich'],
  },
  {
    number: 6,
    series: 'imsa',
    season: 2026,
    team: 'Porsche Penske Motorsport',
    car_model: 'Porsche 963',
    class: 'GTP',
    drivers: ['Laurens Vanthoor', 'Kevin Estre', 'Matthew Campbell'],
  },
  {
    number: 31,
    series: 'imsa',
    season: 2026,
    team: 'Action Express Racing',
    car_model: 'Cadillac V-Series.R',
    class: 'GTP',
    drivers: ['Jack Aitken', 'Earl Bamber', 'Frederik Vesti'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Jack Aitken', 'Earl Bamber', 'Frederik Vesti', 'Connor Zilisch'],
      },
    ],
  },
  {
    number: 24,
    series: 'imsa',
    season: 2026,
    team: 'BMW M Team WRT',
    car_model: 'BMW M Hybrid V8',
    class: 'GTP',
    drivers: ['Sheldon van der Linde', 'Dries Vanthoor'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Sheldon van der Linde', 'Dries Vanthoor', 'Robin Frijns', 'René Rast'],
      },
    ],
  },
  {
    number: 25,
    series: 'imsa',
    season: 2026,
    team: 'BMW M Team WRT',
    car_model: 'BMW M Hybrid V8',
    class: 'GTP',
    drivers: ['Philipp Eng', 'Marco Wittmann'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Philipp Eng', 'Marco Wittmann', 'Kevin Magnussen', 'Raffaele Marciello'],
      },
    ],
  },
  {
    number: 10,
    series: 'imsa',
    season: 2026,
    team: 'Cadillac Wayne Taylor Racing',
    car_model: 'Cadillac V-Series.R',
    class: 'GTP',
    drivers: ['Ricky Taylor', 'Filipe Albuquerque'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Ricky Taylor', 'Filipe Albuquerque', 'Will Stevens'],
      },
    ],
  },
  {
    number: 40,
    series: 'imsa',
    season: 2026,
    team: 'Cadillac Wayne Taylor Racing',
    car_model: 'Cadillac V-Series.R',
    class: 'GTP',
    drivers: ['Jordan Taylor', 'Louis Delétraz'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Jordan Taylor', 'Louis Delétraz', 'Colton Herta'],
      },
    ],
  },
  {
    number: 60,
    series: 'imsa',
    season: 2026,
    team: 'Acura Meyer Shank Racing',
    car_model: 'Acura ARX-06',
    class: 'GTP',
    drivers: ['Tom Blomqvist', 'Colin Braun'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Tom Blomqvist', 'Colin Braun', 'Scott Dixon', 'AJ Allmendinger'],
      },
    ],
  },
  {
    number: 93,
    series: 'imsa',
    season: 2026,
    team: 'Acura Meyer Shank Racing',
    car_model: 'Acura ARX-06',
    class: 'GTP',
    drivers: ['Renger van der Zande', 'Nick Yelloly'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Renger van der Zande', 'Nick Yelloly', 'Alex Palou'],
      },
    ],
  },
  {
    number: 23,
    series: 'imsa',
    season: 2026,
    team: 'Aston Martin THOR Team',
    car_model: 'Aston Martin Valkyrie',
    class: 'GTP',
    drivers: ['Roman De Angelis', 'Ross Gunn'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Roman De Angelis', 'Ross Gunn', 'Alex Riberas', 'Marco Sorensen'],
      },
    ],
  },
  {
    number: 85,
    series: 'imsa',
    season: 2026,
    team: 'JDC-Miller MotorSports',
    car_model: 'Porsche 963',
    class: 'GTP',
    drivers: ['Tijmen van der Helm', 'Nico Pino', 'Kaylen Frederick'],
  },
  {
    number: 2,
    series: 'imsa',
    season: 2026,
    team: 'United Autosports USA',
    car_model: 'ORECA 07',
    class: 'LMP2',
    drivers: ['Phil Fayer', 'Hunter McElrea', 'Mikkel Jensen'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Phil Fayer', 'Ben Hanley', 'Hunter McElrea', 'Mikkel Jensen'],
      },
    ],
  },
  {
    number: 22,
    series: 'imsa',
    season: 2026,
    team: 'United Autosports USA',
    car_model: 'ORECA 07',
    class: 'LMP2',
    drivers: ['Daniel Goldburg', 'Paul Di Resta', 'Rasmus Lindh'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Daniel Goldburg', 'Paul Di Resta', 'Rasmus Lindh', 'Gregoire Saucy'],
      },
    ],
  },
  {
    number: 904,
    series: 'imsa',
    season: 2026,
    team: 'CrowdStrike Racing by APR',
    car_model: 'ORECA 07',
    class: 'LMP2',
    drivers: ['George Kurtz', 'Alex Quinn'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['George Kurtz', 'Alex Quinn', 'Toby Sowery', 'Malthe Jakobsen'],
      },
    ],
  },
  {
    number: 8,
    series: 'imsa',
    season: 2026,
    team: 'Tower Motorsports',
    car_model: 'ORECA 07',
    class: 'LMP2',
    drivers: ['John Farano', 'Tristan Vautier', 'Sebastian Alvarez'],
  },
  {
    number: 11,
    series: 'imsa',
    season: 2026,
    team: 'TDS Racing',
    car_model: 'ORECA 07',
    class: 'LMP2',
    drivers: ['Tobi Lutke', 'David Heinemeier Hansson'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Tobi Lutke', 'Mathias Beche', 'David Heinemeier Hansson', 'Charles Milesi'],
      },
    ],
  },
  {
    number: 18,
    series: 'imsa',
    season: 2026,
    team: 'Era Motorsport',
    car_model: 'ORECA 07',
    class: 'LMP2',
    drivers: ['Naveen Rao', 'Ferdinand Habsburg'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Logan Sargeant', 'Naveen Rao', 'Ferdinand Habsburg', 'Jacob Abel'],
      },
    ],
  },
  {
    number: 37,
    series: 'imsa',
    season: 2026,
    team: 'Intersport Racing',
    car_model: 'ORECA 07',
    class: 'LMP2',
    drivers: ['Jon Field', 'Oliver Jarvis', 'Seth Lucas'],
  },
  {
    number: 43,
    series: 'imsa',
    season: 2026,
    team: 'Inter Europol Competition',
    car_model: 'ORECA 07',
    class: 'LMP2',
    drivers: ['Tom Dillmann', 'Bijoy Garg'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Tom Dillmann', 'Bijoy Garg', 'Antonio Félix da Costa', 'Jeremy Clarke'],
      },
    ],
  },
  {
    number: 52,
    series: 'imsa',
    season: 2026,
    team: 'Bryan Herta Autosport with PR1/Mathiasen',
    car_model: 'ORECA 07',
    class: 'LMP2',
    drivers: ['Misha Goikhberg', 'Harry Tincknell'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Misha Goikhberg', 'Harry Tincknell', 'Parker Thompson', 'Ben Keating'],
      },
    ],
  },
  {
    number: 73,
    series: 'imsa',
    season: 2026,
    team: 'Pratt Miller Motorsports',
    car_model: 'ORECA 07',
    class: 'LMP2',
    drivers: ['Chris Cumming', 'Pietro Fittipaldi', 'Manuel Espirito Santo'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Chris Cumming', 'Pietro Fittipaldi', 'Manuel Espirito Santo', 'Enzo Fittipaldi'],
      },
    ],
  },
  {
    number: 99,
    series: 'imsa',
    season: 2026,
    team: 'AO Racing',
    car_model: 'ORECA 07',
    class: 'LMP2',
    drivers: ['PJ Hyett', 'Dane Cameron'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['PJ Hyett', 'Dane Cameron', 'Jonny Edgar', 'Christian Rasmussen'],
      },
    ],
  },
  {
    number: 343,
    series: 'imsa',
    season: 2026,
    team: 'Inter Europol Competition',
    car_model: 'ORECA 07',
    class: 'LMP2',
    drivers: ['Nick Cassidy', 'Jakub Smiechowski', 'George Kolovos', 'Nolan Siegel'],
  },
  {
    number: 1,
    series: 'imsa',
    season: 2026,
    team: 'Paul Miller Racing',
    car_model: 'BMW M4 GT3',
    class: 'GTD Pro',
    drivers: ['Neil Verhagen', 'Connor De Phillippi'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Neil Verhagen', 'Connor De Phillippi', 'Max Hesse', 'Dan Harper'],
      },
    ],
  },
  {
    number: 3,
    series: 'imsa',
    season: 2026,
    team: 'Corvette Racing by Pratt Miller Motorsports',
    car_model: 'Corvette Z06 GT3.R',
    class: 'GTD Pro',
    drivers: ['Antonio Garcia', 'Alexander Sims'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Antonio Garcia', 'Alexander Sims', 'Marvin Kirchhoefer'],
      },
    ],
  },
  {
    number: 4,
    series: 'imsa',
    season: 2026,
    team: 'Corvette Racing by Pratt Miller Motorsports',
    car_model: 'Corvette Z06 GT3.R',
    class: 'GTD Pro',
    drivers: ['Tommy Milner', 'Nicky Catsburg', 'Nicolas Varrone'],
  },
  {
    number: 9,
    series: 'imsa',
    season: 2026,
    team: 'Pfaff Motorsports',
    car_model: 'Lamborghini Temerario GT3',
    class: 'GTD Pro',
    drivers: ['Andrea Caldarelli', 'Sandy Mitchell'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Andrea Caldarelli', 'Sandy Mitchell', 'Mirko Bortolotti', 'James Hinchcliffe'],
      },
    ],
  },
  {
    number: 14,
    series: 'imsa',
    season: 2026,
    team: 'Vasser Sullivan Racing',
    car_model: 'Lexus RC F GT3',
    class: 'GTD Pro',
    drivers: ['Kyle Kirkwood', 'Jack Hawksworth'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Kyle Kirkwood', 'Jack Hawksworth', 'Ben Barnicoat'],
      },
    ],
  },
  {
    number: 33,
    series: 'imsa',
    season: 2026,
    team: 'Triarsi Competizione',
    car_model: 'Ferrari 296 GT3',
    class: 'GTD Pro',
    drivers: ['Onofrio Triarsi', 'Kenton Koch', 'Robert Megennis'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Onofrio Triarsi', 'Kenton Koch', 'Robert Megennis', 'Yifei Ye'],
      },
    ],
  },
  {
    number: 48,
    series: 'imsa',
    season: 2026,
    team: 'Winward Racing',
    car_model: 'Mercedes-AMG GT3',
    class: 'GTD Pro',
    drivers: ['Scott Noble', 'Jason Hart', 'Luca Stolz', 'Maxime Martin'],
  },
  {
    number: 59,
    series: 'imsa',
    season: 2026,
    team: 'RLL Team McLaren',
    car_model: 'McLaren 720S GT3 EVO',
    class: 'GTD Pro',
    drivers: ['Max Esterson', 'Nikita Johnson'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Max Esterson', 'Nikita Johnson', 'Dean MacDonald', 'Juri Vips'],
      },
    ],
  },
  {
    number: 62,
    series: 'imsa',
    season: 2026,
    team: 'Risi Competizione',
    car_model: 'Ferrari 296 GT3',
    class: 'GTD Pro',
    drivers: ['Daniel Serra', 'Davide Rigon', 'Alessandro Pier Guidi'],
  },
  {
    number: 64,
    series: 'imsa',
    season: 2026,
    team: 'Ford Multimatic Motorsports',
    car_model: 'Ford Mustang GT3',
    class: 'GTD Pro',
    drivers: ['Dennis Olsen', 'Ben Barker'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Dennis Olsen', 'Ben Barker', 'Mike Rockenfeller'],
      },
    ],
  },
  {
    number: 65,
    series: 'imsa',
    season: 2026,
    team: 'Ford Multimatic Motorsports',
    car_model: 'Ford Mustang GT3',
    class: 'GTD Pro',
    drivers: ['Christopher Mies', 'Frédéric Vervisch'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Christopher Mies', 'Frédéric Vervisch', 'Dennis Olsen'],
      },
    ],
  },
  {
    number: 75,
    series: 'imsa',
    season: 2026,
    team: '75 Express',
    car_model: 'Mercedes-AMG GT3',
    class: 'GTD Pro',
    drivers: ['Kenny Habul', 'Maro Engel'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Kenny Habul', 'Maro Engel', 'Chaz Mostert', 'Will Power'],
      },
    ],
  },
  {
    number: 77,
    series: 'imsa',
    season: 2026,
    team: 'AO Racing',
    car_model: 'Porsche 911 GT3 R',
    class: 'GTD Pro',
    drivers: ['Nick Tandy', 'Harry King', 'Alessio Picariello'],
  },
  {
    number: 911,
    series: 'imsa',
    season: 2026,
    team: 'Manthey Racing',
    car_model: 'Porsche 911 GT3 R',
    class: 'GTD Pro',
    drivers: ['Thomas Preining', 'Klaus Bachler', 'Ricardo Feller'],
  },
  {
    number: 12,
    series: 'imsa',
    season: 2026,
    team: 'Vasser Sullivan Racing',
    car_model: 'Lexus RC F GT3',
    class: 'GTD',
    drivers: ['Aaron Telitz', 'Frankie Montecalvo', 'Benjamin Pedersen'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Aaron Telitz', 'Frankie Montecalvo', 'Benjamin Pedersen', 'Esteban Masson'],
      },
    ],
  },
  {
    number: 13,
    series: 'imsa',
    season: 2026,
    team: '13 Autosport',
    car_model: 'Corvette Z06 GT3.R',
    class: 'GTD',
    drivers: ['Orey Fidani', 'Matt Bell', 'Lars Kern'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Orey Fidani', 'Matt Bell', 'Lars Kern', 'Ben Green'],
      },
    ],
  },
  {
    number: 16,
    series: 'imsa',
    season: 2026,
    team: 'Myers Riley Motorsports',
    car_model: 'Ford Mustang GT3',
    class: 'GTD',
    drivers: ['Sheena Monk', 'Felipe Fraga', 'Jenson Altzman'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Sheena Monk', 'Felipe Fraga', 'Jenson Altzman', 'Romain Grosjean'],
      },
    ],
  },
  {
    number: 19,
    series: 'imsa',
    season: 2026,
    team: 'van der Steur Racing',
    car_model: 'Aston Martin Vantage GT3',
    class: 'GTD',
    drivers: ['Rory van der Steur', 'Valentin Hasse-Clot'],
  },
  {
    number: 21,
    series: 'imsa',
    season: 2026,
    team: 'AF Corse USA',
    car_model: 'Ferrari 296 GT3',
    class: 'GTD',
    drivers: ['Simon Mann', 'Lilou Wadoux', 'Antonio Fuoco'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Simon Mann', 'Lilou Wadoux', 'Antonio Fuoco', 'Tommaso Mosca'],
      },
    ],
  },
  {
    number: 23,
    series: 'imsa',
    season: 2026,
    team: 'Triarsi Competizione',
    car_model: 'Ferrari 296 GT3',
    class: 'GTD',
    drivers: ['Onofrio Triarsi', 'Kenton Koch', 'Robert Megennis'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Onofrio Triarsi', 'Kenton Koch', 'Robert Megennis', 'Yifei Ye'],
      },
    ],
  },
  {
    number: 27,
    series: 'imsa',
    season: 2026,
    team: 'Heart of Racing Team',
    car_model: 'Aston Martin Vantage GT3',
    class: 'GTD',
    drivers: ['Tom Gamble', 'Dudu Barrichello', 'Zacharie Robichon'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Tom Gamble', 'Dudu Barrichello', 'Zacharie Robichon', 'Mattia Drudi'],
      },
    ],
  },
  {
    number: 34,
    series: 'imsa',
    season: 2026,
    team: 'Conquest Racing',
    car_model: 'Ferrari 296 GT3',
    class: 'GTD',
    drivers: ['Manny Franco', 'Albert Costa', 'Lorenzo Patrese'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Manny Franco', 'Albert Costa', 'Lorenzo Patrese', 'Thierry Vermuelen'],
      },
    ],
  },
  {
    number: 36,
    series: 'imsa',
    season: 2026,
    team: 'DXDT Racing',
    car_model: 'Corvette Z06 GT3.R',
    class: 'GTD',
    drivers: ['Mason Filippi', 'Charlie Eastwood', 'Salih Yoluc'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Mason Filippi', 'Charlie Eastwood', 'Salih Yoluc', 'Scott McLaughlin'],
      },
    ],
  },
  {
    number: 44,
    series: 'imsa',
    season: 2026,
    team: 'Magnus Racing',
    car_model: 'Aston Martin Vantage GT3',
    class: 'GTD',
    drivers: ['Spencer Pumpelly', 'John Potter', 'Nicki Thiim', 'Madison Snow'],
  },
  {
    number: 45,
    series: 'imsa',
    season: 2026,
    team: 'Wayne Taylor Racing',
    car_model: 'Lamborghini Huracán GT3 EVO2',
    class: 'GTD',
    drivers: ['Kyle Marcelli', 'Danny Formal'],
  },
  {
    number: 57,
    series: 'imsa',
    season: 2026,
    team: 'Winward Racing',
    car_model: 'Mercedes-AMG GT3',
    class: 'GTD',
    drivers: ['Russell Ward', 'Philip Ellis', 'Indy Dontje'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Russell Ward', 'Philip Ellis', 'Indy Dontje', 'Lucas Auer'],
      },
    ],
  },
  {
    number: 66,
    series: 'imsa',
    season: 2026,
    team: 'Gradient Racing',
    car_model: 'Ford Mustang GT3',
    class: 'GTD',
    drivers: ['Jake Walker', 'Corey Lewis'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Jake Walker', 'Corey Lewis', 'Joey Hand', 'Till Bechtolsheimer'],
      },
    ],
  },
  {
    number: 70,
    series: 'imsa',
    season: 2026,
    team: 'Inception Racing',
    car_model: 'Ferrari 296 GT3',
    class: 'GTD',
    drivers: ['Brendan Iribe', 'Frederik Schandorff', 'Ollie Millroy'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Brendan Iribe', 'Frederik Schandorff', 'Ollie Millroy', 'David Fumanelli'],
      },
    ],
  },
  {
    number: 80,
    series: 'imsa',
    season: 2026,
    team: 'Lone Star Racing',
    car_model: 'Mercedes-AMG GT3',
    class: 'GTD',
    drivers: ['Scott Andrews', 'Lin Hodenius', 'James Roe', 'Ralf Aron'],
  },
  {
    number: 81,
    series: 'imsa',
    season: 2026,
    team: 'DragonSpeed',
    car_model: 'Corvette Z06 GT3.R',
    class: 'GTD',
    drivers: ['Henrik Hedman', 'Giacomo Altoe', 'Casper Stevenson'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Henrik Hedman', 'Giacomo Altoe', 'Casper Stevenson', 'Matteo Cairoli'],
      },
    ],
  },
  {
    number: 83,
    series: 'imsa',
    season: 2026,
    team: 'RS1',
    car_model: 'Porsche 911 GT3 R',
    class: 'GTD',
    drivers: ['Jon Field', 'Misha Goikhberg', 'Parker Thompson'],
  },
  {
    number: 96,
    series: 'imsa',
    season: 2026,
    team: 'Turner Motorsport',
    car_model: 'BMW M4 GT3',
    class: 'GTD',
    drivers: ['Robby Foley', 'Patrick Gallagher', 'Francis Selldorff'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Robby Foley', 'Patrick Gallagher', 'Francis Selldorff', 'Jens Klingmann'],
      },
    ],
  },
  {
    number: 120,
    series: 'imsa',
    season: 2026,
    team: 'Wright Motorsports',
    car_model: 'Porsche 911 GT3 R',
    class: 'GTD',
    drivers: ['Adam Adelson', 'Callum Ilott', 'Tom Sargent'],
    driverOverrides: [
      {
        race: 'Rolex 24 at Daytona',
        drivers: ['Adam Adelson', 'Callum Ilott', 'Tom Sargent', 'Elliott Skeer'],
      },
    ],
  },
  {
    number: 912,
    series: 'imsa',
    season: 2026,
    team: 'Manthey 1st Phorm',
    car_model: 'Porsche 911 GT3 R',
    class: 'GTD',
    drivers: ['Ryan Hardwick', 'Riccardo Pera', 'Richard Lietz', 'Morris Schuring'],
  },

];

export function getCarByNumber(number, series, season, raceName = null) {
  const entry = raceTeams.find(
    car => car.number === number && car.series === series && car.season === season
  );

  if (!entry) return null;
  if (!raceName || !entry.driverOverrides) return entry;

  const override = entry.driverOverrides.find(o => o.race === raceName);
  if (!override) return entry;

  return { ...entry, drivers: override.drivers };
}